### ✅ Criar usuário
POST http://localhost:3000/api/v1/user/
Content-Type: application/json

{
  "name": "Miguel Junior",
  "email": "miguelsilvanogjr@gmail.com",
  "password": "senhadificil"
}

###

### 📋 Listar todos os usuários
GET http://localhost:3000/api/v1/auth

###

### 🔍 Buscar um usuário por ID
GET http://localhost:3000/api/v1/auth/681d4fadeea2bef0dae25923

###

### ✏️ Atualizar um usuário por ID
PUT http://localhost:3000/api/v1/auth/681d4fadeea2bef0dae25923
Content-Type: application/json

{
  "name": "João Atualizado",
  "email": "joao.novo@email.com"
}

###

### ❌ Deletar um usuário por ID
DELETE http://localhost:3000/api/v1/auth/681d4fadeea2bef0dae25923
